### ISSUE TITLE
Node doesn't syncing

### ISSUE THREAD

**Issue by njuice** [tonlabs/net.ton.dev#18]
Hi. 
After installation node doesn't syncing with a lot of same messages in the log:

`[ 2][t 5][1589655555.102943897][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][1589655556.522623301][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][1589655557.890264750][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
[ 2][t 4][1589655557.943520069][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][1589655561.938862085][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
[ 2][t 5][1589655565.666907549][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][1589655565.961014032][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
[ 2][t 4][1589655570.009113789][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
[ 2][t 4][1589655571.399553061][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 6][1589655572.013873339][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
[ 2][t 4][1589655576.058635712][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,0)]	failed to download state : [Error : 652 : adnl query timeout]
`

**Comment by ar-tmp** [comment]
Is it still actual?
Such errors may appear right after node start but then it should begin syncing.
Make sure you use SSD and your network throughput is enough (1Gb/sec+)

**Comment by njuice** [comment]
It seems, there was a network issue. 
Firstly I have checked firewalls, ports, etc. on the server, but nothing helped. Most likely the problem was on the internet provider side because on another machine all works.
So, it not actual anymore for me, but if someone will have a similar issue - just start to dig from the internet connection check.
