### ISSUE TITLE
Node unexpectedly crashed

### ISSUE THREAD

**Issue by samorodkin** [tonlabs/net.ton.dev#20]
Here is a node.log tail:

```
[ 2][t 6][1590078551.268077850][check-proof.cpp:46][!checkprooflink][&VALIDATOR_WARNING]        aborting check proof for [ w=0 s=15564440312192434176 seq=246606 7+tREn60ju09PCLX/HSe7/R4I+7IjV5zuwdx7s8+NFs= ZPklZXVcazG/Y9lBpbTOmnCa6UEIrRyaYBqwvnEpMsw= ] query: [Error : 651 : timeout]
[ 3][t 3][1590078551.268093348][wait-block-state.cpp:187][!checkprooflink]      received bad proof link: [Error : 651 : timeout]
[ 3][t 6][1590078551.268104553][wait-block-state.cpp:187][!checkprooflink]      received bad proof link: [Error : 651 : timeout]
[ 2][t 3][1590078551.268289089][Timer.cpp:82][!checkprooflink][&duration > max_duration_]       SLOW: [name:checkproof][duration:28.7s]
[ 2][t 6][1590078551.268302679][Timer.cpp:82][!checkprooflink][&duration > max_duration_]       SLOW: [name:checkproof][duration:28.5s]
[ 2][t 6][1590078551.268370628][check-proof.cpp:46][!checkprooflink][&VALIDATOR_WARNING]        aborting check proof for [ w=0 s=15564440312192434176 seq=246608 0URCeBCIni+APBIkEegoWoD0dk7SF2Dy6zgaW1Fw6Qg= D2xy5N6BvRQAHRpN2HOTuZs3MaxyiGm7Gj8AaQogXfs= ] query: [Error : 651 : timeout]
[ 2][t 3][1590078551.268381357][check-proof.cpp:46][!checkprooflink][&VALIDATOR_WARNING]        aborting check proof for [ w=0 s=15564440312192434176 seq=246607 ktd1eLHWe5vXLVL6JILsZ7GL9L8xu194PiQTymeB2pk= AwkM34jzjLDq8KaP/FnC0KmUZ6OUT5dqrgc9BKECqPk= ] query: [Error : 651 : timeout]
[ 3][t 6][1590078551.268398762][wait-block-state.cpp:187][!checkprooflink]      received bad proof link: [Error : 651 : timeout]
[ 3][t 3][1590078551.268411636][wait-block-state.cpp:187][!checkprooflink]      received bad proof link: [Error : 651 : timeout]
[ 2][t 6][1590078551.268431664][Timer.cpp:82][!checkprooflink][&duration > max_duration_]       SLOW: [name:checkproof][duration:24.3s]
[ 2][t 3][1590078551.268470526][Timer.cpp:82][!checkprooflink][&duration > max_duration_]       SLOW: [name:checkproof][duration:26.0s]
[ 2][t 6][1590078551.268506289][check-proof.cpp:46][!checkprooflink][&VALIDATOR_WARNING]        aborting check proof for [ w=-1 s=9223372036854775808 seq=180005 d/5i+7pJqNt7M20B9DUbJPc/GyxBL8ZE5KKT08NqCT4= Z5EXE/+KIMvG2CmWEyRCoID5P+INgs4IYlv2+S391Bg= ] query: [Error : 651 : timeout]
[ 3][t 6][1590078551.268526793][wait-block-state.cpp:187][!checkprooflink]      received bad proof link: [Error : 651 : timeout]
[ 2][t 6][1590078551.268544197][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=180005 d/5i+7pJqNt7M20B9DUbJPc/GyxBL8ZE5KKT08NqCT4= Z5EXE/+KIMvG2CmWEyRCoID5P+INgs4IYlv2+S391Bg= ] priority=2: [Error : 652 : timeout]
[ 2][t 6][1590078551.268577576][Timer.cpp:82][!checkprooflink][&duration > max_duration_]       SLOW: [name:checkproof][duration:24.2s]
[ 2][t 7][1590078551.268639803][Timer.cpp:82][!broadcast][&duration > max_duration_]    SLOW: [name:validatebroadcast][duration:15.0s]
------- Stack Backtrace -------
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x1fd7a1)[0x563e5e36d7a1]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x1fa56e)[0x563e5e36a56e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f6a2c763890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f6a2b857e97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f6a2b859801]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x210207)[0x563e5e380207]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x210de5)[0x563e5e380de5]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x21009a)[0x563e5e38009a]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x4b73ef)[0x563e5e6273ef]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x68f03b)[0x563e5e7ff03b]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x69c109)[0x563e5e80c109]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x220b2a)[0x563e5e390b2a]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x220d7d)[0x563e5e390d7d]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x230e58)[0x563e5e3a0e58]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(+0x223786)[0x563e5e393786]
/home/dmitry/net.ton.dev/ton/build/validator-engine/validator-engine(_ZN2td6detail13ThreadPthread10run_threadEPv+0x37)[0x563e5e2bd627]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f6a2c7586db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f6a2b93a88f]
-------------------------------
```

**Comment by ar-tmp** [comment]
Is it still actual?
If yes could you please send more detailed log file?

**Comment by samorodkin** [comment]
No more crashes yes. Do you need just longer log tail or as per neighbor issue to increase verbosity (validator-engine-console -a 127.0.0.1:3030 -k ~/ton-keys/client -p ~/ton-keys/server.pub -c "setverbosity 10" -c "quit")  ?

**Comment by ar-tmp** [comment]
If the issue happens again please send us node.log with more lines (1000) before the crash and default verbosity level.

**Comment by Proguser** [comment]
I have this problem too. The node falls after a few hours of work already 5 days.

**Comment by ASLanin** [comment]
Same issue reported at #25 
Continuing there as it's better documented.

**Comment by vcvetkovs** [comment]
game3: 

> [ 2][t 8][1594548504.001817703][adnl-peer.cpp:526][!catchainreceiver]   failed to answer query: [Error : 651 : db not read]
> [ 2][t 4][1594548504.094907522][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ] priority=2: [Error : 602 : db error:  state already gc'd]
> [ 2][t 4][1594548504.094936371][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.094945431][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.094954491][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=3 wBqZlt3Lhhj2vHiu7AVda4celQ0K/5NfV+lL6KLft2E= 7lh9Owx+F1OCJGDDpxJblw8Dl5+UDotjE/dJ/YQ92P8= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.095044851][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=4 Nn0f1e7g3zxHbME4nL93FMYYrEuU8N5L0iH4lDjIiBM= jAq4ROIeTVX/+Iocub5JeFOTbUVFfyINaXbmTbM8040= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=3 wBqZlt3Lhhj2vHiu7AVda4celQ0K/5NfV+lL6KLft2E= 7lh9Owx+F1OCJGDDpxJblw8Dl5+UDotjE/dJ/YQ92P8= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
