### ISSUE TITLE
Connection refused : 111 : Error on [fd:5]] conn failed

### ISSUE THREAD

**Issue by boo50** [tonlabs/net.ton.dev#22]
I've got connection error already two times.
Validator node worked for a week and suddenly got error, all attempts to restart give this error
After that create new build with new working dirs and it's connected successfully, but after 2 days got same error.
And again I can start another build with clean setup and working dirs, but this one won't connect.

connecting to [127.0.0.1:3030]
local key: B156EF991E7B32FB2891654E12DEDC4736B06548AC309C99546194452B6663EC
remote key: 7F0549BDEAC3B7F350D00A9F340668BDB10B50AE23FE7E24751135674C97EFC6
[ 1][t 0][1590632653.744904518][adnl-ext-connection.cpp:129][!outconn] Client got error [PosixError : Connection refused : 111 : Error on [fd:5]]
conn failed
[ 1][t 0][1590632663.755304575][adnl-ext-connection.cpp:129][!outconn] Client got error [PosixError : Connection refused : 111 : Error on [fd:5]]
conn failed
[ 1][t 0][1590632673.765874624][adnl-ext-connection.cpp:129][!outconn] Client got error [PosixError : Connection refused : 111 : Error on [fd:5]]
conn failed
[ 1][t 0][1590632683.772887945][adnl-ext-connection.cpp:129][!outconn] Client got error [PosixError : Connection refused : 111 : Error on [fd:5]]
conn failed

full node log provided below
https://anonfiles.com/1dX2z438o4/node_log

**Comment by ar-tmp** [comment]
Could you please restart the node from scratch (backup wallet files, remove /var/ton-work and ~/ton-keys).
If the node crashes again please save the log file at the moment of 1st crash and send it to us.

**Comment by ASLanin** [comment]
Closed due to Inactivity

**Comment by boo50** [comment]
I've seen some users are reporting same error, but nobody share his logs.
I got this error today so I want to share log to find issue.

Looks like db is corrupted after node crash

Failed to load cell from db[Error : 0 : Corruption: block checksum mismatch: expected 2028804236, got    3206494874  in /var/ton-work/db/celldb//000939.sst offset 33024757 size 4076]^[[0m

here are last lines of node.log
https://anonfiles.com/v6z7z2C5oc/nodefail3_log
