### ISSUE TITLE
The node falls after a few hours of work

### ISSUE THREAD

**Issue by Proguser** [tonlabs/net.ton.dev#25]
After the transfer to new equipment, the node constantly falls. Cleaning and reinstalling does not help. Please deal with the reason.
[node_4.log.gz](https://github.com/tonlabs/net.ton.dev/files/4774784/node_4.log.gz)

**Comment by ar-tmp** [comment]
What was changed during the transfer?

**Comment by Proguser** [comment]
Provider vps and increased productivity.  From the old node I took only the keys and wallet address.

**Comment by ar-tmp** [comment]
I suppose node IP address was changed?
If there's new IP I'd recommend you to start the node from scratch (with new keys but you can use old wallet).

**Comment by Proguser** [comment]
I don’t understand how the IP address affects sudden stops of a node. She correctly signs the blocks for 3-4 hours, and then crumbles.

**Comment by ASLanin** [comment]
Thank you for the report. We are currently investigating this issue.

**Comment by vcvetkovs** [comment]
Same machine, same IP, after latest update (9July) node writes very huge amount of log which started with

> [ 2][t 8][1594548504.001817703][adnl-peer.cpp:526][!catchainreceiver]   failed to answer query: [Error : 651 : db not read]
> [ 2][t 4][1594548504.094907522][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ] priority=2: [Error : 602 : db error:  state already gc'd]
> [ 2][t 4][1594548504.094936371][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.094945431][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.094954491][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=3 wBqZlt3Lhhj2vHiu7AVda4celQ0K/5NfV+lL6KLft2E= 7lh9Owx+F1OCJGDDpxJblw8Dl5+UDotjE/dJ/YQ92P8= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> [ 2][t 4][1594548504.095044851][wait-block-state.cpp:36][!waitstate]    aborting wait block state query for [ w=-1 s=9223372036854775808 seq=4 Nn0f1e7g3zxHbME4nL93FMYYrEuU8N5L0iH4lDjIiBM= jAq4ROIeTVX/+Iocub5JeFOTbUVFfyINaXbmTbM8040= ] priority=2: [Error : 602 : prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=3 wBqZlt3Lhhj2vHiu7AVda4celQ0K/5NfV+lL6KLft2E= 7lh9Owx+F1OCJGDDpxJblw8Dl5+UDotjE/dJ/YQ92P8= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=2 JQcuQ2sjtoFgjnjF1I2eKviU5EYh3V2znKRR/NVJ+34= m+71/YYtwKpmlRgU6M6VjX05R3cM2AiA3yecf6PcWUY= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=1 /kwkCOdKWQoUWuSgeRdcSctUbxeV7NX6W4LwWxUHlXc= UGo/zmvWICrsxhdfjOLT3lr5iUWCbx4FrBurfTSigc0= ]:  prev state wait error:  failed to download state [ w=-1 s=9223372036854775808 seq=0 E1n42FXn3MNUFPIyxfvPw2YCKR8Mv2T0BObD3xbgiYc= 3ZqeoZbvHWEAwCt1zZ4ky2qpFp3iVHEgdCTqxeNfHmY= ]:  db error:  state already gc'd]
> 

it just comes sequentially trough each 'seq' and wraps previous message, this is how logs are growing, I have got speed about 3-4GB/sec, of course node crashed and log occupied all free space.

**Comment by ar-tmp** [comment]
Is it still actual? If yes lets try to flush DB.
- stop validator-engine
- backup /var/ton-work/db
- remove everything except config.json and keyring folder in /var/ton-work/db
- start the node
- wait for node sync up

**Comment by ar-tmp** [comment]
Closing because there's no answer - please re-open the issue if it's actual.
