### ISSUE TITLE
rights mask no right

### ISSUE THREAD

**Issue by PSpiel** [tonlabs/net.ton.dev#27]
after ./setup.sh I find that the folder  ~/ton-keys/elections is missing the x-bit for the user.
drw------- 2 ton ton 4096 Jun 17 19:00 elections

that breaks the validator-msig.sh script to my undertanding... maybe even more

you can manually correct by issuing the command
chmod u+x ~/ton-keys/elections/
but I think it would be better to fix the mask in the scripts directly

**Comment by artemr-tl** [comment]
setup.sh is run only during initial node setup procedure. If node is deployed and you need to re-run setup.sh just backup (e.g. due to wallet files) and clean ~/ton-keys manually. 
Thank you for reporting. We'll add a check in setup.sh for that.

**Comment by ar-tmp** [comment]
`elections` folder is usually created by the validator script (not related to `setup.sh`). User's umask is something outside of the current scripts and configured by users.
Closing the issue - if it's still actual please re-open.
