### ISSUE TITLE
issue with build ton_executor

### ISSUE THREAD

**Issue by boo50** [tonlabs/net.ton.dev#30]
Tried fresh build today and got error about ton_executor:

`error[E0432]: unresolved imports `ton_block::GasFlatPfx`, `ton_block::GasPrices`, `ton_block::GasPricesEx`
  --> /home/tontest/.cargo/git/checkouts/ton-labs-executor-1c02eaf6bb19aa83/1f7e80b/src/blockchain_config.rs:17:5
   |
17 |     GasFlatPfx, GasLimitsPrices, GasPrices, GasPricesEx, Message, MsgAddressInt,
   |     ^^^^^^^^^^                   ^^^^^^^^^  ^^^^^^^^^^^ no `GasPricesEx` in the root
   |     |                            |
   |     |                            no `GasPrices` in the root
   |     no `GasFlatPfx` in the root

error[E0599]: no associated item named `Std` found for struct `ton_block::config_params::GasLimitsPrices` in the current scope
   --> /home/tontest/.cargo/git/checkouts/ton-labs-executor-1c02eaf6bb19aa83/1f7e80b/src/blockchain_config.rs:260:30
    |
260 |             GasLimitsPrices::Std(prices) => prices.into(),
    |                              ^^^ associated item not found in `ton_block::config_params::GasLimitsPrices`

error[E0599]: no associated item named `Ex` found for struct `ton_block::config_params::GasLimitsPrices` in the current scope
   --> /home/tontest/.cargo/git/checkouts/ton-labs-executor-1c02eaf6bb19aa83/1f7e80b/src/blockchain_config.rs:261:30
    |
261 |             GasLimitsPrices::Ex(prices) => prices.into(),
    |                              ^^ associated item not found in `ton_block::config_params::GasLimitsPrices`

error[E0599]: no associated item named `FlatPfx` found for struct `ton_block::config_params::GasLimitsPrices` in the current scope
   --> /home/tontest/.cargo/git/checkouts/ton-labs-executor-1c02eaf6bb19aa83/1f7e80b/src/blockchain_config.rs:262:30
    |
262 |             GasLimitsPrices::FlatPfx(prices) => prices.into(),
    |                              ^^^^^^^ associated item not found in `ton_block::config_params::GasLimitsPrices`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `ton_executor`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by fiktor** [comment]
See also https://github.com/tonlabs/ton-labs-executor/issues/2 .

**Comment by ASLanin** [comment]
Fixed tonlabs/ton-labs-executor#2
