### ISSUE TITLE
Script validator_msig.sh can't see tokens for return.

### ISSUE THREAD

**Issue by finderom** [tonlabs/net.ton.dev#31]
Script validator_msig.sh can't see tokens for return if begin work same seconds after begin election.
Election already start, but tokens not unlocked. 

For example:
Election start 04:09:48  but script run in  04:10:00

Out of log file: 
INFO: validator_msig.sh BEGIN 1594429801 / Sat Jul 11 03:10:01 CEST 2020
INFO: MSIG_ADDR = -1:....
INFO: recover_amount = 0 nanotokens
INFO: nothing to recover
INFO: 2020-07-11 03:10:01 Elections 1594462556

But after 10 minutes script successfull returned tokens.

May be script have to wait  some seconds after election start?

**Comment by ASLanin** [comment]
Actual blockchain time is always a little behind the Unix time.
Usual lag is 5-15s.
Run the script a minute later after the start of the election.
