### ISSUE TITLE
Please change validator_msig.sh for FreeBSD compatibility

### ISSUE THREAD

**Issue by Custler** [tonlabs/net.ton.dev#33]
base64 on FreeBSD and some other systems has not '--wrap' key  
so please change 
recover_query_boc=$(base64 --wrap=0 "${ELECTIONS_WORK_DIR}/recover-query.boc") 
to 
**recover_query_boc=$(base64 "${ELECTIONS_WORK_DIR}/recover-query.boc" | tr -d "\n")**
and 
validator_query_boc=$(base64 --wrap=0 "${ELECTIONS_WORK_DIR}/validator-query.boc")
to 
**validator_query_boc=$(base64 "${ELECTIONS_WORK_DIR}/validator-query.boc" |tr -d "\n")**

for compatibility

**Comment by ar-tmp** [comment]
Fixed.
